### ISSUE TITLE
This lib Is Amazing!

### ISSUE THREAD

**Issue by s0kil** [vaneenige/phenomenon#9]
What does phenomenon do to achieve such smoothness? Compared to other WebGL libraries?

**Comment by vaneenige** [comment]
Hey Daniel, thank you! 

_Phenomenon is smooth because it runs almost entirely on the GPU with no overhead._ 

If you take a look at the examples it might surprise you that all the particles or cubes are a single geometry. They all move around based on a single value (`uniform`) that is send to the GPU on every frame. Scaling up to 100K particles will still result in a single geometry so it doesn't slow down in a way that it would with 100K geometries.
